### ISSUE TITLE
Metadata for netCDF files created by WCS requests

### ISSUE THREAD

**Issue by huard** [ECCC-CCCS/geomet-climate#36]
Hi !

Our team would like to use WCS requests to fetch operational forecasts and feed them to an hydrological model. While this works at the moment, it would be nice for variables to have descriptive names (instead of Band1) and attributes. 

Is this something that can be reasonably done and how someone new to the code base could contribute to this ?

**Comment by RousseauLambertLP** [comment]
Hi David, 

You are talking about the metadata in the resulting WCS NetCDF file right ? 

If so, we already looked in it, and it's not a trivial change to add metadata in a NetCDF from a WCS request with GeoMet...

The thing is we use MapServer as our cartographic server and we use it to create our WCS outputs. MapServer uses GDAL to manipulate and generate the NetCDF WCS output and GDAL does not allow much flexibility when writing a NetCDF file. If you want to change the file structure (band vs Subdataset) or add metadata for the NetCDF to be CF compliant for example, you need to do an extra step (using NetCDF librairies) of processing which is not handled by MapServer.

Since we don't want to do this kind of processing on the fly for every NetCDF WCS request, our idea was to use the  evolving OGC API standards and [pygeoapi](https://pygeoapi.io/) for future implementation. It might be processes, it might just be coverages, since we could do our own provider based on netcdf-python.

If you want more information or are interesting on contributing on that front, let us know, it would surely help us !

**Comment by huard** [comment]
Correct !

Yes, we'd certainly be interested in contributing to see this happening. Let us know what we could do to move this forward.

**Comment by richardarsenault** [comment]
@RousseauLambertLP @huard 

Hi! @julemai and I might have some ideas on how to process and/or provide some information and codes to help out with this point. We think it could be interesting to discuss this on a call. Would you be available next week (July 14/15/ 16) after 14:00 EST?

Thanks and have a good day!

**Comment by RousseauLambertLP** [comment]
Hi, sorry this week is full for us (@tomkralidis and I) but next week on Monday or Tuesday at 14:00 EST could work ?

**Comment by richardarsenault** [comment]
Hi @RousseauLambertLP  and @tomkralidis, 

I sent an invite to your email address but I guess it didn't go through. Here is an invite for 2PM on Monday, if that still works for you: https://etsmtl.zoom.us/j/93571827386 

Thanks and looking forward to discussing this with you!

**Comment by huard** [comment]
Hi all, 

To work around the metadata issue, our strategy is now to fetch forecasts in grib format from the datamart, convert to them to netCDF and expose then as NcML from our THREDDS server. This allows us to add metadata attributes easily, but ideally we would use metadata provided by ECCC. So for example, if we expose GEPS data, what should be the global attributes (https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#description-of-file-contents) ?  

- title
- institution
- source
- history
- references
- comment
